/**
 * OAuth Authorization Server API
 * Definition of the REST API exported by the OAuth Authorization Server.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Wrapper for error responses.
 */
export interface ModelError { 
    /**
     * Type of the error that has happened.
     */
    errorType: string;
    /**
     * Reason of the error that has happened.
     */
    errorReason: string;
}

