/**
 * OAuth Authorization Server API
 * Definition of the REST API exported by the OAuth Authorization Server.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JWKSetKeys { 
    /**
     * The \"kid\" (key ID) parameter is used to match a specific key.
     */
    kid?: string;
    /**
     * The \"kty\" (key type) parameter identifies the cryptographic algorithm family used with the key, such as \"RSA\" or \"EC\".
     */
    kty?: JWKSetKeys.KtyEnum;
    /**
     * The \"alg\" (algorithm) parameter identifies the algorithm intended for use with the key.
     */
    alg?: JWKSetKeys.AlgEnum;
    /**
     * The \"key_ops\" (key operations) parameter identifies the operation(s) for which the key is intended to be used.
     */
    key_ops?: Array<JWKSetKeys.KeyOpsEnum>;
    /**
     * The \"use\" (public key use) parameter identifies the intended use of the public key.
     */
    use?: JWKSetKeys.UseEnum;
    /**
     * Values that conform the RSA Public key.
     */
    e?: string;
    /**
     * Values that conform the RSA Public key.
     */
    n?: string;
}
export namespace JWKSetKeys {
    export type KtyEnum = 'RSA';
    export const KtyEnum = {
        RSA: 'RSA' as KtyEnum
    };
    export type AlgEnum = 'RS512';
    export const AlgEnum = {
        RS512: 'RS512' as AlgEnum
    };
    export type KeyOpsEnum = 'verify';
    export const KeyOpsEnum = {
        Verify: 'verify' as KeyOpsEnum
    };
    export type UseEnum = 'sig';
    export const UseEnum = {
        Sig: 'sig' as UseEnum
    };
}

