/**
 * OAuth Authorization Server API
 * Definition of the REST API exported by the OAuth Authorization Server.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response sent back by the Authorization Server when an OAuth token request is performed.
 */
export interface OAuthTokenResponse { 
    /**
     * Access token for the client and user, which can be used to access Resource Servers. It's a JWT token, which can be decoded with the Authorization Server public key.
     */
    accessToken: string;
    /**
     * The type of token this is, typically just the string “bearer”.
     */
    tokenType: string;
    /**
     * Time in seconds until token expiration.
     */
    expiresIn: number;
}

