/**
 * OAuth Authorization Server API
 * Definition of the REST API exported by the OAuth Authorization Server.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response sent back by the Authorization Server when an OAuth authorization request is performed.
 */
export interface OAuthAuthorizeResponse { 
    /**
     * Authorization Code sent to the callback so it can be used to obtain an access token. Token is encrypted so only the Authorization Server can access the token information.
     */
    code: string;
    /**
     * URL of the client where the UI should redirect the user to complete the authorization flow. This url contains all the required query params.
     */
    redirect_uri: string;
}

