/**
 * OAuth Authorization Server API
 * Definition of the REST API exported by the OAuth Authorization Server.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuthTokenInput { 
    /**
     * The grant type for the Authentication Flow required.
     */
    grant_type: OAuthTokenInput.GrantTypeEnum;
    /**
     * Authorization Code received by the Authorize phase. (Authorization Code Flow - REQUIRED)
     */
    code?: string;
    /**
     * Must be identical to the redirect URI used in the Authorization phase. (Authorization Code Flow - REQUIRED)
     */
    redirect_uri?: string;
    /**
     * Unique identifier of the client that requests the access token.
     */
    client_id: string;
    /**
     * The client’s secret. This ensures that the request to get the access token is made only from the client. (Authorization Code Flow - OPTIONAL, Client Credentials Flow - REQUIRED)
     */
    client_secret?: string;
    /**
     * The user’s username that they entered in the client application. (Password Flow - REQUIRED)
     */
    username?: string;
    /**
     * The user’s password that they entered in the client application. (Password Flow - REQUIRED)
     */
    password?: string;
    /**
     * The code verifier for the PKCE request that the app originally generated before the authorization request. (Authorization Code Flow - OPTIONAL)
     */
    code_verifier?: string;
    /**
     * One or more scope values indicating which parts of the user's account the client wish to access. (Password and Client Credentials Flows - OPTIONAL)
     */
    scope?: string;
}
export namespace OAuthTokenInput {
    export type GrantTypeEnum = 'authorization_code' | 'password' | 'client_credentials';
    export const GrantTypeEnum = {
        AuthorizationCode: 'authorization_code' as GrantTypeEnum,
        Password: 'password' as GrantTypeEnum,
        ClientCredentials: 'client_credentials' as GrantTypeEnum
    };
}

