/**
 * OAuth Authorization Server API
 * Definition of the REST API exported by the OAuth Authorization Server.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Credentials of the user to authenticate.
 */
export interface UserLoginInput { 
    /**
     * Username of the user to authenticate.
     */
    username: string;
    /**
     * Password of the user to authenticate.
     */
    password: string;
}

